# 
#   Copyright (C) 1993, 1994, 1995, 1996 Free Software Foundation
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2, or (at
#   your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

dir := hurd
makemode := misc

DIST_FILES = *.defs subsystems ioserver.h ports.h pager.h fshelp.h \
	diskfs.h trivfs.h cthreads.h netfs.h
LCLHDRS = hurd_types.h ioctl_types.h paths.h shared.h version.h

include ../Makeconf

