# Copyright (C) 1991 Free Software Foundation, Inc.
# This file is part of the GNU Hurd.
# 
# The GNU Hurd is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# The GNU Hurd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with the GNU Hurd; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

GCC_EXEC_PREFIX=/usr/local/lib/gcc-
MIGCOM=../mig/migcom
MK_INCLUDES=/usr1/mk/release/i386_mach/latest/include
CPPFLAGS=-nostdinc -I. -I.. -I${MK_INCLUDES} -D__USE_GNU -D__GNU_SYSTEM

headers: fs.h io.h auth.h fsys.h misc.h name.h process.h socket.h term.h

