#!/bin/bash
# Setup critical hurd translators

set -v

# Set up the PFLOCAL server so we can do pipes
/bin/settrans -c /servers/socket/1 /hurd/pflocal

# Setup crucial devices
cd /dev
/bin/sh ./MAKEDEV std
