# 
#   Copyright (C) 1994 Free Software Foundation
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2, or (at
#   your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

dir := libtrivfs

include ../Makeconf

DIST_FILES= demuxer.c dir-link.c dir-mkdir.c dir-mkfile.c dir-pathtrans.c \
	dir-readdir.c dir-rename.c dir-rmdir.c dir-unlink.c file-chauthor.c \
	file-chflags.c file-chmod.c file-chown.c file-get-trans.c \
	file-get-transcntl.c file-getcontrol.c file-getfh.c file-getlinknode.c\
	file-lock.c file-pathconf.c file-set-trans.c file-statfs.c \
	file-sync.c file-syncfs.c file-truncate.c file-utimes.c fsys-getroot.c\
	fsys-goaway.c fsys-stubs.c init.c interrupt.c io-async-icky.c \
	io-async.c io-duplicate.c io-map.c io-modes-get.c io-modes-off.c \
	io-modes-on.c io-modes-set.c io-owner-get.c io-owner-mod.c io-read.c \
	io-readable.c io-reauthenticate.c io-restrict-auth.c io-seek.c \
	io-select.c io-stat.c io-stubs.c io-version.c io-write.c nosenders.c \
	notify-stubs.c trivfs.h
