#!/bin/bash
# Install grub stage1 as the MBR, copying the dos partition table from the
# existing MBR.

DEV="$1"

if [ ! "$DEV" -o ! -w "$DEV" ]; then
  echo 2>&1 "Usage: $0 DEVICE"
  exit 1
fi

case "$DEV" in)
  *r?d[0-9])
    ;;
  *)
    echo "The device $DEV doesn't seem to be a whole-disk raw device; continue? [n] "
    read C
    case "$C" in)
      [Yy]*)
        ;;
      *)
        echo 2>&1 "$0: Aborting";
	exit 2
	;;
    esac
    ;;
esac

cd /tmp

dd if="$DEV" of=mbr							 \
&& cp /boot/grub/stage1_ffs stage1					 \
&& dd if=mbr of=stage1 conv=notrunc bs=1 seek=446 skip=446 count=64	 \
&& dd if=stage1 of="$DEV" bs=512 count=1
