#!/bin/bash
# Setup critical hurd translators

set -v

# Make sure the filesystem is writable
fsysopts / --writable 

# Set up standard passive translators
/bin/settrans -c /servers/socket/local /hurd/pflocal
/bin/settrans -c /servers/crash /hurd/crash

# Setup crucial devices
cd /dev
/bin/sh ./MAKEDEV std ptyp ptyq

echo 'Hit ^C now for shell prompt or RET to reboot'
read response
sync
reboot
